/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Clases.ActualizarDatosBD;
import Clases.IsertarDatosBD2;
import Clases.internalFrameImagen;
import static formularios.frmPrincipal.Dpanel;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class ExpedienteO extends internalFrameImagen {
IsertarDatosBD2 i=new IsertarDatosBD2();
    /**
     * Creates new form ExpedienteO
     */
    public ExpedienteO() {
        initComponents();
        setImagenw("img2.jpg");

            ExpedienteO.txtanguloA1.setEnabled(false);
            ExpedienteO.txtanguloG1.setEnabled(false);
            ExpedienteO.txtIMPA1.setEnabled(false);
            ExpedienteO.txtJa1.setEnabled(false);
            ExpedienteO.txtEJE.setEnabled(false);
            ExpedienteO.txtIS.setEnabled(false);
            ExpedienteO.txtII.setEnabled(false);
            ExpedienteO.txtFHIS.setEnabled(false);
            ExpedienteO.txtANB82.setEnabled(false);
            ExpedienteO.txtANB80.setEnabled(false);
            ExpedienteO.txtANB2.setEnabled(false);
            ExpedienteO.txtPALS.setEnabled(false);
            ExpedienteO.txtPALI.setEnabled(false);
            ExpedienteO.txtPTB.setEnabled(false);
            ExpedienteO.txtDSD.setEnabled(false);
            ExpedienteO.txtmaxilares.setEnabled(false);
            ExpedienteO.txtEntornoD.setEnabled(false);
            ExpedienteO.txtbandas.setEnabled(false);
            ExpedienteO.txttubos.setEnabled(false);
            ExpedienteO.txtotros.setEnabled(false);
            ExpedienteO.txtAparato.setEnabled(false);
            ExpedienteO.txtexodoncia.setEnabled(false);
            ExpedienteO.txtBrakets.setEnabled(false);
            ExpedienteO.txtRetenciones.setEnabled(false);
            ExpedienteO.txtsecuencia.setEnabled(false);
            ExpedienteO.txtMD.setEnabled(false);
            ExpedienteO.txtrocabado.setEnabled(false);
            ExpedienteO.btnguardar.setEnabled(false);
            ExpedienteO.btneditar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jLabel82 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtEJE = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtanguloA1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtanguloG1 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtIMPA1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtJa1 = new javax.swing.JTextField();
        txtIS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        txtII = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtFHIS = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtANB82 = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        txtPALS = new javax.swing.JTextField();
        txtANB80 = new javax.swing.JTextField();
        txtANB2 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        txtPALI = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        txtPTB = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        lblnombre10 = new javax.swing.JLabel();
        chcurvaleve1 = new javax.swing.JCheckBox();
        chcurvamoderada1 = new javax.swing.JCheckBox();
        chcurvasevera = new javax.swing.JCheckBox();
        lblnombre6 = new javax.swing.JLabel();
        txtDSD = new javax.swing.JTextField();
        lblnombre9 = new javax.swing.JLabel();
        lblnombre8 = new javax.swing.JLabel();
        txtmaxilares = new javax.swing.JTextField();
        lblnombre7 = new javax.swing.JLabel();
        txtEntornoD = new javax.swing.JTextField();
        lblnombre11 = new javax.swing.JLabel();
        txtbandas = new javax.swing.JTextField();
        lblnombre12 = new javax.swing.JLabel();
        txttubos = new javax.swing.JTextField();
        lblnombre13 = new javax.swing.JLabel();
        txtotros = new javax.swing.JTextField();
        lblnombre14 = new javax.swing.JLabel();
        txtAparato = new javax.swing.JTextField();
        lblnombre15 = new javax.swing.JLabel();
        txtexodoncia = new javax.swing.JTextField();
        lblnombre17 = new javax.swing.JLabel();
        txtBrakets = new javax.swing.JTextField();
        lblnombre19 = new javax.swing.JLabel();
        txtRetenciones = new javax.swing.JTextField();
        lblnombre18 = new javax.swing.JLabel();
        txtsecuencia = new javax.swing.JTextField();
        lblnombre20 = new javax.swing.JLabel();
        txtMD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel87 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator67 = new javax.swing.JSeparator();
        chmodelo = new javax.swing.JCheckBox();
        chfaciales = new javax.swing.JCheckBox();
        chpanoramica = new javax.swing.JCheckBox();
        chintraorales = new javax.swing.JCheckBox();
        jSeparator68 = new javax.swing.JSeparator();
        chmodeloMD = new javax.swing.JCheckBox();
        chcefalometrica = new javax.swing.JCheckBox();
        chincicivos = new javax.swing.JCheckBox();
        jSeparator69 = new javax.swing.JSeparator();
        jSeparator70 = new javax.swing.JSeparator();
        txtrocabado = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnguardar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnpaciente = new javax.swing.JButton();
        lblnombre = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lbnombre = new javax.swing.JLabel();
        lbapellido = new javax.swing.JLabel();
        lbidcefa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        lbid = new javax.swing.JLabel();
        lbidplan = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel82.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel82.setText("Expediente Ortodoncia");
        getContentPane().add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 280, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 116, 10, 110));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 116, 1140, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 226, 1140, 10));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 1140, 10));

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 116, -1, 110));

        jLabel3.setText("IS-LS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 126, 30, -1));

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 176, 1140, 20));

        jLabel4.setText("4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 156, 30, -1));

        txtEJE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEJEActionPerformed(evt);
            }
        });
        getContentPane().add(txtEJE, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 196, 59, -1));

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 116, 20, 110));

        jLabel5.setText("Angulo Articular");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 126, 80, -1));

        jLabel6.setText("150°");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 156, 34, -1));

        txtanguloA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanguloA1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtanguloA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 196, 59, -1));

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 116, 30, 110));

        jLabel7.setText("Angulo Goniaco Inferior");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 126, 120, -1));

        jLabel8.setText("75°");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 156, 20, -1));

        jLabel9.setText("75°");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 156, 20, -1));

        txtanguloG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanguloG1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtanguloG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 196, 59, -1));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 116, 30, 110));

        jLabel18.setText("IMPA");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 126, 30, -1));

        jLabel19.setText("85-93-97°");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 156, 50, -1));

        txtIMPA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIMPA1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtIMPA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 196, 59, -1));

        jLabel20.setText("Porcentaje JARABAK");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 126, -1, -1));

        jLabel21.setText("EJE FACIAL");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 126, 60, -1));

        jLabel22.setText("56%");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 156, 30, -1));

        jLabel23.setText("90");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 156, 20, -1));

        txtJa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJa1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtJa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 196, 59, -1));

        txtIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISActionPerformed(evt);
            }
        });
        getContentPane().add(txtIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 196, 59, -1));

        jLabel24.setText("II-LS");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 126, 30, -1));

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 116, 10, 110));

        jLabel25.setText("0");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 156, 10, -1));

        txtII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIIActionPerformed(evt);
            }
        });
        getContentPane().add(txtII, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 196, 59, -1));

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 116, 10, 110));

        jLabel26.setText("FHIS");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 126, 30, -1));

        jLabel27.setText("110°-115°");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 156, -1, -1));

        txtFHIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFHISActionPerformed(evt);
            }
        });
        getContentPane().add(txtFHIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 196, 59, -1));

        jSeparator19.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 116, 10, 110));

        jSeparator20.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 116, 90, 110));

        jLabel28.setText("ANB");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 126, 30, -1));

        jLabel29.setText("2°");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 156, 20, -1));

        txtANB82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANB82ActionPerformed(evt);
            }
        });
        getContentPane().add(txtANB82, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 196, 20, -1));

        jSeparator21.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 116, 10, 110));

        jSeparator22.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 116, 10, 110));

        jLabel30.setText("82°");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 156, 20, -1));

        jLabel31.setText("80°");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 156, 20, -1));

        jLabel32.setText("PALS");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 126, 30, -1));

        jLabel33.setText("4 mm");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 156, 30, -1));

        jSeparator24.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 146, 10, 80));

        jSeparator25.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 146, 10, 80));

        txtPALS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPALSActionPerformed(evt);
            }
        });
        getContentPane().add(txtPALS, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 196, 59, -1));

        txtANB80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANB80ActionPerformed(evt);
            }
        });
        getContentPane().add(txtANB80, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 196, 20, -1));

        txtANB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANB2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtANB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 196, 20, -1));

        jLabel78.setText("PALI");
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 126, 40, -1));

        jLabel79.setText("2 mm");
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 156, 30, 20));

        txtPALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPALIActionPerformed(evt);
            }
        });
        getContentPane().add(txtPALI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 196, 59, -1));

        jSeparator23.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 116, 10, 110));

        jLabel80.setText("PTB");
        getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 126, 30, -1));

        jLabel81.setText("-3 mm");
        getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 156, 30, -1));

        txtPTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPTBActionPerformed(evt);
            }
        });
        getContentPane().add(txtPTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 196, 59, -1));

        jSeparator26.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 116, 10, 110));

        jSeparator27.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 116, 10, 110));

        jSeparator28.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 1140, 10));

        lblnombre10.setText("Curva de Spee: ");
        getContentPane().add(lblnombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 242, 80, -1));

        chcurvaleve1.setText("Leve");
        getContentPane().add(chcurvaleve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 242, 60, -1));

        chcurvamoderada1.setText("Moderada");
        getContentPane().add(chcurvamoderada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 242, 80, -1));

        chcurvasevera.setText("Severa");
        getContentPane().add(chcurvasevera, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 242, 70, -1));

        lblnombre6.setText("DSD:");
        getContentPane().add(lblnombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 242, 40, -1));
        getContentPane().add(txtDSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 242, 60, -1));

        lblnombre9.setText("mm.");
        getContentPane().add(lblnombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 242, 30, -1));

        lblnombre8.setText("Clasificación Maxilares:");
        getContentPane().add(lblnombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 268, -1, -1));
        getContentPane().add(txtmaxilares, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 268, 380, -1));

        lblnombre7.setText("Entorno Dental:");
        getContentPane().add(lblnombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 268, -1, -1));
        getContentPane().add(txtEntornoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 268, 380, -1));

        lblnombre11.setText("Bandas en:");
        getContentPane().add(lblnombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 346, 60, 20));
        getContentPane().add(txtbandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 346, 380, -1));

        lblnombre12.setText("tubos:");
        getContentPane().add(lblnombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 376, 40, 10));
        getContentPane().add(txttubos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 376, 380, -1));

        lblnombre13.setText("Otros:");
        getContentPane().add(lblnombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 406, 40, 20));

        txtotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotrosActionPerformed(evt);
            }
        });
        getContentPane().add(txtotros, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 406, 380, -1));

        lblnombre14.setText("Aparato tipo:");
        getContentPane().add(lblnombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 436, 70, 20));
        getContentPane().add(txtAparato, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 436, 380, -1));

        lblnombre15.setText("Exodoncia:");
        getContentPane().add(lblnombre15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 476, 60, 20));
        getContentPane().add(txtexodoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 476, 380, -1));

        lblnombre17.setText("Brackets:");
        getContentPane().add(lblnombre17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 514, 50, 20));

        txtBrakets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBraketsActionPerformed(evt);
            }
        });
        getContentPane().add(txtBrakets, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 514, 380, -1));

        lblnombre19.setText("RETENCIONES MX:");
        getContentPane().add(lblnombre19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 554, 100, 20));

        txtRetenciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetencionesActionPerformed(evt);
            }
        });
        getContentPane().add(txtRetenciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 554, 380, -1));

        lblnombre18.setText("Secuencia de Arcos:");
        getContentPane().add(lblnombre18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 584, 100, 20));
        getContentPane().add(txtsecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 584, 380, -1));

        lblnombre20.setText("MD:");
        getContentPane().add(lblnombre20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 624, 30, 20));
        getContentPane().add(txtMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 624, 380, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Indicacion especial antes de colocar Brackets");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 330, -1));

        jLabel83.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel83.setText("Plan de Tratamiento");
        getContentPane().add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 400, 10));

        jLabel84.setText("Tomar imp.");
        getContentPane().add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 60, -1));

        jLabel85.setText("Repetir Fotos");
        getContentPane().add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 80, -1));

        jLabel86.setText("Tomar Rx");
        getContentPane().add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 50, -1));

        jSeparator29.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 400, -1));

        jSeparator30.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 400, 50));

        jLabel87.setText("RX Rocabado");
        getContentPane().add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 80, -1));

        jSeparator31.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 400, 20));

        jSeparator32.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator32.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator32.setToolTipText("");
        getContentPane().add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 60, 130));

        jSeparator33.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator33.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, -1, 90));

        jSeparator67.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator67.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator67, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, -1, 90));

        chmodelo.setText("Modelo mx ");
        getContentPane().add(chmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 93, -1));

        chfaciales.setText("Faciales");
        getContentPane().add(chfaciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, -1, -1));

        chpanoramica.setText("Panoramica");
        getContentPane().add(chpanoramica, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 93, -1));

        chintraorales.setText("Intraorales");
        getContentPane().add(chintraorales, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, 93, -1));

        jSeparator68.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator68.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator68, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 380, -1, 90));

        chmodeloMD.setText("Modelo md");
        getContentPane().add(chmodeloMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 93, -1));

        chcefalometrica.setText("Cefalometrica");
        getContentPane().add(chcefalometrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, 93, -1));

        chincicivos.setText("Incicivos");
        getContentPane().add(chincicivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 440, 70, -1));

        jSeparator69.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator69.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator69, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 380, -1, 130));

        jSeparator70.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator70, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 400, -1));

        txtrocabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrocabadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtrocabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 280, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 534, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setToolTipText("");
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 12, 320));

        btnguardar.setForeground(new java.awt.Color(0, 0, 204));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 530, -1, 90));

        btnsalir.setForeground(new java.awt.Color(0, 0, 204));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 530, -1, 90));

        btnpaciente.setForeground(new java.awt.Color(0, 0, 204));
        btnpaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/elegir tp.png"))); // NOI18N
        btnpaciente.setText("Elegir paciente para tratamiento");
        btnpaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 14, -1, -1));
        getContentPane().add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 75, 135, -1));
        getContentPane().add(lblapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 75, 135, -1));
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1174, 81, -1, -1));
        getContentPane().add(lbnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 87, 18, 18));
        getContentPane().add(lbapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 87, 130, 18));
        getContentPane().add(lbidcefa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 57, 18));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Para poder continuar debe elegir un paciente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setToolTipText("");
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1200, -1));

        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar edicion.png"))); // NOI18N
        jButton1.setText("Buscar paciente para editar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, 90));
        getContentPane().add(lbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1101, 87, 57, 18));
        getContentPane().add(lbidplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 57, 18));

        btneditar.setForeground(new java.awt.Color(0, 0, 204));
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEJEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEJEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEJEActionPerformed

    private void txtanguloA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanguloA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanguloA1ActionPerformed

    private void txtanguloG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanguloG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanguloG1ActionPerformed

    private void txtIMPA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIMPA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIMPA1ActionPerformed

    private void txtJa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJa1ActionPerformed

    private void txtISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISActionPerformed

    private void txtIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIIActionPerformed

    private void txtFHISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFHISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFHISActionPerformed

    private void txtANB82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANB82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANB82ActionPerformed

    private void txtPALSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPALSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPALSActionPerformed

    private void txtANB80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANB80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANB80ActionPerformed

    private void txtANB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANB2ActionPerformed

    private void txtPALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPALIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPALIActionPerformed

    private void txtPTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPTBActionPerformed

    private void txtotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotrosActionPerformed

    private void txtBraketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBraketsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBraketsActionPerformed

    private void txtRetencionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetencionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetencionesActionPerformed

    private void txtrocabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrocabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrocabadoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        //validaciones
        if (this.lbnombre.getText().length()==0 || this.lbapellido.getText().length()==0|| this.lbidcefa.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Debe elegir un paciente");
        }else{
            
        String articular=this.txtanguloA1.getText();
        String goniaco=this.txtanguloG1.getText();
        String impa=this.txtIMPA1.getText();
        String jarabak=this.txtJa1.getText();
        String facial=this.txtEJE.getText();
        String is=this.txtIS.getText();
        String ii=this.txtII.getText();
        String fhis=this.txtFHIS.getText();
        String anb82=this.txtANB82.getText();
        String anb80=this.txtANB80.getText();
        String anb2=this.txtANB2.getText();
        String pals=this.txtPALS.getText();
        String pali=this.txtPALI.getText();
        String ptb=this.txtPTB.getText();
        String Consulta_id_consulta = this.lbidcefa.getText();
        int seleccion = 0;
        if(this.chcurvaleve1.isSelected()== true ) {
             seleccion = 1;
            }else{
            seleccion = 0;
        }
        int speeleve= seleccion;
         int seleccion1 = 0;
        if(this.chcurvamoderada1.isSelected()== true ) {
             seleccion1 = 1;
            }else{
            seleccion1 = 0;
        }
        int speemoderada= seleccion1;
          int seleccion2 = 0;
        if(this.chcurvasevera.isSelected()== true ) {
             seleccion2 = 1;
            }else{
            seleccion2 = 0;
        }
        int speesvera= seleccion2;
        String dsd= this.txtDSD.getText();
        String clasim= this.txtmaxilares.getText();
        String entornod= this.txtEntornoD.getText();
      
        IsertarDatosBD2 insertar2 = new IsertarDatosBD2();
        insertar2.insertor(articular,goniaco,impa,jarabak,facial,is,ii,fhis,anb82,anb80,anb2,pals,pali,ptb,speeleve,speemoderada,speesvera,
                    dsd,clasim,entornod,Consulta_id_consulta);
        
        
        String bandas = this.txtbandas.getText();
        String tubos = this.txttubos.getText();
        String otros = this.txtotros.getText();
        String aparato = this.txtAparato.getText();
        String exodoncia = this.txtexodoncia.getText();
        String brackets = this.txtBrakets.getText();
        String retenciones = this.txtRetenciones.getText();
        String arcos = this.txtsecuencia.getText();
        String md = this.txtMD.getText();
        //validacion chfaciales
        int seleccion3 = 0;
        if(this.chfaciales.isSelected()== true ) {
             seleccion3 = 1;
            }else{
            seleccion3 = 0;
        }
        int f_faciales= seleccion3;
        // validaciones chintraorales
        int seleccion4 = 0;
        if(this.chintraorales.isSelected()== true ) {
             seleccion4 = 1;
            }else{
            seleccion4 = 0;
        }
        int f_intraorales = seleccion4;
        //validacion chmodelo
        int seleccion5 = 0;
        if(this.chmodelo.isSelected()== true ) {
             seleccion5 = 1;
            }else{
            seleccion5 = 0;
        }
        int modelo_mx = seleccion5;
        //validacion chmodeloMD
        int seleccion6 = 0;
        if(this.chmodeloMD.isSelected()== true ) {
             seleccion6 = 1;
            }else{
            seleccion6 = 0;
        }
        int modelo_md = seleccion6;
        //validacion chpanoramica
        int seleccion7 = 0;
        if(this.chpanoramica.isSelected()== true ) {
             seleccion7 = 1;
            }else{
            seleccion7 = 0;
        }
        int rx_panoramica = seleccion7;
        //validacion chcefalometrica
        int seleccion8 = 0;
        if(this.chcefalometrica.isSelected()== true ) {
             seleccion8 = 1;
            }else{
            seleccion8 = 0;
        }
        int rx_cefalometria = seleccion8;
        //validacion chincicivos
         int seleccion9 = 0;
        if(this.chincicivos.isSelected()== true ) {
             seleccion9 = 1;
            }else{
            seleccion9 = 0;
        }
        int rx_incicivos = seleccion9;
        String rx_rocabado = this.txtrocabado.getText();
        
        IsertarDatosBD2 insertar = new IsertarDatosBD2();
        insertar.insertartrata(bandas, tubos, otros, aparato, exodoncia, brackets, retenciones, arcos, md, f_faciales, f_intraorales, modelo_mx, modelo_md, rx_panoramica, rx_cefalometria, rx_incicivos, rx_rocabado, Consulta_id_consulta);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpacienteActionPerformed
       frmvistapacienteTO formExGral = new frmvistapacienteTO();
       Dpanel.add(formExGral);
       formExGral.show();
    }//GEN-LAST:event_btnpacienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      frmEditarOrtodoncia formExGral = new frmEditarOrtodoncia();
       Dpanel.add(formExGral);
       formExGral.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
          String articular = this.txtanguloA1.getText().toUpperCase();
          String goniaco = this.txtanguloG1.getText().toUpperCase();
          String impa = this.txtIMPA1.getText().toUpperCase();
          String jarabak = this.txtJa1.getText().toUpperCase();
          String facial = this.txtEJE.getText().toUpperCase();
          String is = this.txtIS.getText().toUpperCase();
          String ii = this.txtII.getText().toUpperCase();
          String fhis = this.txtFHIS.getText().toUpperCase();
          String anb82 = this.txtANB82.getText().toUpperCase();
          String anb80 = this.txtANB80.getText().toUpperCase();
          String anb2 = this.txtANB2.getText().toUpperCase();
          String pals = this.txtPALS.getText().toUpperCase();
          String pali = this.txtPALI.getText().toUpperCase();
          String ptb = this.txtPTB.getText().toUpperCase();
          String dsd = this.txtDSD.getText().toUpperCase();
          String clasim = this.txtmaxilares.getText().toUpperCase();
          String entornod = this.txtEntornoD.getText().toUpperCase();
          int code = Integer.valueOf(this.lbidcefa.getText());
          ActualizarDatosBD actpaciente = new ActualizarDatosBD();
          actpaciente.ActualizarCefalometria(articular, goniaco, impa, jarabak, facial, is, ii, fhis, anb82, anb80, anb2, pals, pali, ptb, dsd, clasim, entornod, code);
         
          String bandas = this.txtbandas.getText().toUpperCase();
          String tubos = this.txttubos.getText().toUpperCase();
          String otros = this.txtotros.getText().toUpperCase();
          String aparato = this.txtAparato.getText().toUpperCase();
          String exodoncia = this.txtexodoncia.getText().toUpperCase();
          String brackets = this.txtBrakets.getText().toUpperCase();
          String retenciones = this.txtRetenciones.getText().toUpperCase();
          String arcos = this.txtsecuencia.getText().toUpperCase();
          String md = this.txtMD.getText().toUpperCase();
          String rocabado = this.txtrocabado.getText().toUpperCase();
          int code1 = Integer.valueOf(this.lbidplan.getText());
          
          ActualizarDatosBD actpaciente1 = new ActualizarDatosBD();
          actpaciente1.ActualizarPlanTrata(bandas, tubos, otros, aparato, exodoncia, brackets, retenciones, arcos, md, rocabado, code1);
          
          
    }//GEN-LAST:event_btneditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btneditar;
    public static javax.swing.JButton btnguardar;
    public static javax.swing.JButton btnpaciente;
    private javax.swing.JButton btnsalir;
    private javax.swing.JCheckBox chcefalometrica;
    private javax.swing.JCheckBox chcurvaleve1;
    private javax.swing.JCheckBox chcurvamoderada1;
    private javax.swing.JCheckBox chcurvasevera;
    private javax.swing.JCheckBox chfaciales;
    private javax.swing.JCheckBox chincicivos;
    private javax.swing.JCheckBox chintraorales;
    private javax.swing.JCheckBox chmodelo;
    private javax.swing.JCheckBox chmodeloMD;
    private javax.swing.JCheckBox chpanoramica;
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator67;
    private javax.swing.JSeparator jSeparator68;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator70;
    private javax.swing.JSeparator jSeparator8;
    public static javax.swing.JLabel lbapellido;
    public static javax.swing.JLabel lbid;
    public static javax.swing.JLabel lbidcefa;
    public static javax.swing.JLabel lbidplan;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombre10;
    private javax.swing.JLabel lblnombre11;
    private javax.swing.JLabel lblnombre12;
    private javax.swing.JLabel lblnombre13;
    private javax.swing.JLabel lblnombre14;
    private javax.swing.JLabel lblnombre15;
    private javax.swing.JLabel lblnombre17;
    private javax.swing.JLabel lblnombre18;
    private javax.swing.JLabel lblnombre19;
    private javax.swing.JLabel lblnombre20;
    private javax.swing.JLabel lblnombre6;
    private javax.swing.JLabel lblnombre7;
    private javax.swing.JLabel lblnombre8;
    private javax.swing.JLabel lblnombre9;
    public static javax.swing.JLabel lbnombre;
    public static javax.swing.JTextField txtANB2;
    public static javax.swing.JTextField txtANB80;
    public static javax.swing.JTextField txtANB82;
    public static javax.swing.JTextField txtAparato;
    public static javax.swing.JTextField txtBrakets;
    public static javax.swing.JTextField txtDSD;
    public static javax.swing.JTextField txtEJE;
    public static javax.swing.JTextField txtEntornoD;
    public static javax.swing.JTextField txtFHIS;
    public static javax.swing.JTextField txtII;
    public static javax.swing.JTextField txtIMPA1;
    public static javax.swing.JTextField txtIS;
    public static javax.swing.JTextField txtJa1;
    public static javax.swing.JTextField txtMD;
    public static javax.swing.JTextField txtPALI;
    public static javax.swing.JTextField txtPALS;
    public static javax.swing.JTextField txtPTB;
    public static javax.swing.JTextField txtRetenciones;
    public static javax.swing.JTextField txtanguloA1;
    public static javax.swing.JTextField txtanguloG1;
    public static javax.swing.JTextField txtbandas;
    public static javax.swing.JTextField txtexodoncia;
    public static javax.swing.JTextField txtmaxilares;
    public static javax.swing.JTextField txtotros;
    public static javax.swing.JTextField txtrocabado;
    public static javax.swing.JTextField txtsecuencia;
    public static javax.swing.JTextField txttubos;
    // End of variables declaration//GEN-END:variables
}
